# Experiment Parameters
root_dir: /mnt/projects/debruinz_project/integration/tensorboard
config_name: config.yaml

experiment_name: summer_merge_testing/long_runs

predict_dir: samples

model: configs/model/config.yaml
data: configs/data/local.yaml
trainer: configs/trainer/config.yaml

categories: 
- 'donor_id'
- 'assay'
- 'dataset_id' 
- 'cell_type'

merge_keys:
- z


# ENVIROMENT SPECIFIC
env_path: '/mnt/projects/debruinz_project/pytorch-nightly-env/bin/python3'
