# Experiment Parameters
root_dir: lightning_logs

config_name: config.yaml
experiment_name: experiment
run_name: default_run

predict_dir: samples

model: configs/model/config.yaml
data: configs/data/local.yaml
trainer: configs/trainer/config.yaml

categories: 
- 'donor_id'
- 'assay'
- 'dataset_id' 
- 'cell_type'

merge_keys:
- z


# ENVIROMENT SPECIFIC
env_path: /mnt/projects/debruinz_project/pytorch-nightly-env/bin/python3
