# Experiment Parameters
root_dir: lightning_logs

config_name: config.yaml
experiment_name: experiment
run_name: ""

predict_dir: samples

categories:
- 'donor_id'
- 'assay'
- 'dataset_id'
- 'cell_type'

merge_keys:
- z
