# .pre-commit-config.yaml

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        stages: [commit, manual]
        args: [src]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        stages: [commit, manual]
        args: [src]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.7.4
    hooks:
      - id: pylint
        stages: [manual]
        args: [src]
