# lightning.pytorch==2.2.5
class_path: sciml.models.MMVAEModel
init_args:
  module: 
    class_path: sciml.modules.MMVAE
    init_args:
      vae:
        class_path: sciml.modules.VAE
        init_args:
          n_in: 1024
          encoder_layers:
           - 512
           - 256
          n_latent: 128
          decoder_layers:
           - 256
           - 512
          n_out: 1024
          distribution: normal
      experts:
        class_path: sciml.modules.base.Experts
        init_args: 
          human_encoder_kwargs:
            layers:
             - 60664
             - 1024
            dropout_rate: 0.1
          human_decoder_kwargs:
            layers:
            - 1024
            - 60664
          mouse_encoder_kwargs:
            layers:
            - 52417
            - 1024
          mouse_decoder_kwargs:
            layers:
             - 1024
             - 52417
