name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Python 3.9.18
      uses: actions/setup-python@v5
      with:
        python-version: "3.9.18"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Ensure docs directory exists
      run: mkdir -p ./docs

    - name: Generate Documentation
      run: ./scripts/auto-doc.sh

    - name: List docs directory
      run: ls -al ./docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs  