# Workflow for building and deploying static content to GitHub Pages
name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - development
      - feature/*
      - summer_merge

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.18' 

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml', 'setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install project and doc dependencies
        run: |
          pip install -e .[doc]
      
      - name: Generate HTML documentation with pdoc
        run: ./scripts/auto-doc.sh

      - name: Rename docs folder for branch-specific deployment
        if: github.ref_name != 'main'
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          mv docs "docs-${BRANCH_NAME}"
          
      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.ref_name == 'main' && 'docs' || "docs-${github.ref_name}" }}
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4