# Workflow for building and deploying static content to GitHub Pages
name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - development
      - feature/*
      - summer_merge

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.18' 

      - name: Cache virtual environment
        id: cache-python
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'setup.cfg') }}
          restore-keys: |
            venv-${{ runner.os }}-
      
      - name: Set up virtual environment
        if: steps.cache-python.outputs.cache-hit != 'True'
        run: python -m venv .venv
      
      - name: Activate virtual environment
        run: source .venv/bin/activate

      - name: Install project+test dependencies
        if: steps.cache-python.outputs.cache-hit != 'True'
        run: |
          pip install --upgrade pip
          pip install -e .[test,doc]
      
      - name: Generate HTML documentation with pdoc
        run: ./scripts/auto-doc.sh

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
          name: gh-pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: gh-pages-${{ github.ref_name }}