name: CMMVAE Unit Tests
run-name: Running tests on modules in the CMMVAE package
on:
  push:
    branches:
      - main
      - dev
      - feature/*

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.18' 

      - name: Cache pip dependencies
        id: cache-python
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'setup.cfg') }}
          restore-keys: |
            venv-${{ runner.os }}-
      
      - name: Set up virtual environment
        if: steps.cache-python.outputs.cache-hit != 'True'
        run: python -m venv .venv
      
      - name: Activate virtual environment
        run: source .venv/bin/activate

      - name: Install all project dependencies
        if: steps.cache-python.outputs.cache-hit != 'True'
        run: |
          pip install --upgrade pip
          pip install -e .[test,doc]

      - name: Run unit tests with coverage
        run: pytest --cov=cmmvae tests