name: MMVAE Unit Tests
run-name: Running tests on modules in the MMVAE package
on: [ push ]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3.9.18
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.18"
      - name: Set up Python environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install project+test dependencies
        run: pip3 install -e .[test]
      - name: Run unit tests with coverage
        env:
          PYTHONPATH: .
        run: pytest --cov=cmmvae tests/